namespace CMSResources {
    /// <summary>
    /// Auto-generated ID constants for CMS content.
    /// Generated by CMSIdGenerator. Do not edit manually.
    /// Run CMS > Generate ID Registry before building the game.
    /// </summary>
    public static class CMSIdRegistry {

        public const string Butterfly = "Butterfly";
        public const string Player = "Player";
        public const string TreeLog = "TreeLog";
    }
}
