#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace CMSResources {
    internal static class CMSIdGenerator {
        private static string OutputPath => Path.Combine(Application.dataPath, "CMSIdRegistry.cs");

        public static void Generate() {
            if (!Directory.Exists(CMSConstants.LocalCMSPath)) {
                Debug.LogError($"[CMS] CMS folder not found: {CMSConstants.LocalCMSPath}");
                return;
            }

            var ids = new SortedDictionary<string, string>();
            
            // Collect data file IDs from Configs/
            if (Directory.Exists(CMSConstants.ConfigsPath))
                CollectIds(CMSConstants.ConfigsPath, ids);
            
            // Collect asset file IDs from CMS root
            CollectIds(CMSConstants.LocalCMSPath, ids);

            if (ids.Count == 0) {
                Debug.LogWarning("[CMS] No files found to generate IDs.");
                return;
            }

            string code = GenerateCode(ids);
            File.WriteAllText(OutputPath, code);
            AssetDatabase.Refresh();
            Debug.Log($"[CMS] Generated CMSIdRegistry with {ids.Count} IDs at {OutputPath}");
        }

        private static void CollectIds(string rootPath, SortedDictionary<string, string> ids) {
            if (!Directory.Exists(rootPath)) 
                return;

            var allFiles = Directory.GetFiles(rootPath, "*.*", SearchOption.AllDirectories);
            var skipExts = new[] { ".meta", ".cs", ".md", ".dll" };

            foreach (var file in allFiles) {
                string ext = Path.GetExtension(file).ToLowerInvariant();
                if (skipExts.Contains(ext)) continue;

                string id = Path.GetFileNameWithoutExtension(file);
                string name = ToConstantName(id);

                if (!string.IsNullOrEmpty(name))
                    ids.TryAdd(name, id);
            }
        }

        private static string ToConstantName(string id) {
            var parts = id.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();
            foreach (var part in parts) {
                if (part.Length == 0) continue;
                sb.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1) sb.Append(part.Substring(1));
            }
            return sb.ToString();
        }

        private static string GenerateCode(SortedDictionary<string, string> ids) {
            var sb = new StringBuilder();
            sb.AppendLine($"namespace CMSResources {{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated ID constants for CMS content.");
            sb.AppendLine("    /// Generated by CMSIdGenerator. Do not edit manually.");
            sb.AppendLine("    /// Run CMS > Generate ID Registry before building the game.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class CMSIdRegistry {");

            var grouped = new SortedDictionary<string, List<KeyValuePair<string, string>>>();
            foreach (var kv in ids) {
                string folder = ResolveFolder(kv.Value);
                if (!grouped.ContainsKey(folder))
                    grouped[folder] = new List<KeyValuePair<string, string>>();
                grouped[folder].Add(kv);
            }

            foreach (var group in grouped) {
                sb.AppendLine();
                foreach (var kv in group.Value)
                    sb.AppendLine($"        public const string {kv.Key} = \"{kv.Value}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string ResolveFolder(string id) {
            // First check Configs subfolders for data files
            if (Directory.Exists(CMSConstants.ConfigsPath)) {
                var folders = Directory.GetDirectories(CMSConstants.ConfigsPath);
                foreach (var folder in folders) {
                    var name = Path.GetFileName(folder);
                    var files = Directory.GetFiles(folder, "*.*", SearchOption.TopDirectoryOnly);
                    foreach (var file in files)
                        if (Path.GetFileNameWithoutExtension(file) == id) return name;
                }
            }
            
            // Then check CMS root for assets
            if (Directory.Exists(CMSConstants.LocalCMSPath)) {
                var files = Directory.GetFiles(CMSConstants.LocalCMSPath, "*.*", SearchOption.TopDirectoryOnly);
                foreach (var file in files)
                    if (Path.GetFileNameWithoutExtension(file) == id) return "Root";
                
                // Check subfolders under CMS root (e.g. Prefabs/)
                var subFolders = Directory.GetDirectories(CMSConstants.LocalCMSPath);
                foreach (var folder in subFolders) {
                    if (folder.EndsWith("Configs")) 
                        continue;
                    var name = Path.GetFileName(folder);
                    var subFiles = Directory.GetFiles(folder, "*.*", SearchOption.TopDirectoryOnly);
                    foreach (var file in subFiles)
                        if (Path.GetFileNameWithoutExtension(file) == id) return name;
                }
            }
            return "Other";
        }
    }
}
#endif
